### ISSUE TITLE
Innecessary check in triangle_range.

### ISSUE THREAD

**Issue by zyth0s** [jagot/AngularMomentumAlgebra.jl#8]
https://github.com/JuliaAtoms/AngularMomentumAlgebra.jl/blob/b2fb0adc9c0da0104b11006675963cb9f3a5736f/src/common.jl#L12
I can't think of a situation where the above cited expression is evaluated. For instance
```julia
function check(a,b)
    kmin = abs(a-b)
    !iseven(kmin + a + b)
end

@assert any([check(a,b) for a in -15:15 for b in -15:15]) == false
```
IHMO, it can be safely removed.

**Comment by jagot** [comment]
Thanks for your interest!

If `a` and `b` are half-integers, e.g. `a=3/2` and `b=1/2`, then `|a-b| == 1`. Granted, it is not used that way at the moment, but it might happen in the future.
